model:
  base_learning_rate: 5.0e-5   # set to target_lr by starting main.py with '--scale_lr False'
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 1000
    timesteps: 1000
    loss_type: l1
    first_stage_key: image
    cond_stage_key: specmap
    image_size: 32
    channels: 3
    cond_stage_trainable: True
    conditioning_key: concat #crossattn #
    #concat_mode: False
    #scale_by_std: True
    monitor: 'val/loss_simple_ema'

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [ 1.]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:

        image_size: 32
        in_channels: 6
        out_channels: 3
        model_channels: 128
        attention_resolutions:
          - 8
          - 4
          - 2
        num_res_blocks: 2
        channel_mult:
          - 1
          - 2
          - 3
          - 4
        num_heads: 1


    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 3
        monitor: "val/rec_loss"
        ckpt_path: "./logs/brainAE/checkpoints/last.ckpt"
        ddconfig:
          double_z: True
          z_channels: 3
          resolution: 128
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.Spatialremap64  #Spatialremap64




data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 1
    wrap: False
    train:
      target: ldm.data.spectral_data_2.SPECTrain
      params:
        size: 128
    validation:
      target: ldm.data.spectral_data_2.SPECValidation
      params:
        size: 128

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2000
        max_images: 8
        increase_log_steps: False


  trainer:
    benchmark: True
    accumulate_grad_batches: 1
    gpus: '0'
    max_epochs: 50